version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    machine: true  # ✅ Required for Docker-in-Docker
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest

  deploy_to_gke:
    machine: true  # ✅ Needed for kubectl and gcloud
    steps:
      - checkout

      - run:
          name: Install kubectl and GKE Auth Plugin
          command: |
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --client

            echo "Installing GKE Auth Plugin..."
            # Add Google Cloud SDK repo and key
            sudo apt-get update -y && sudo apt-get install -y apt-transport-https ca-certificates gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
              sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
              sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
            sudo apt-get update -y
            sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/region $GOOGLE_COMPUTE_REGION
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Configure GKE Cluster
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER \
              --region $GOOGLE_COMPUTE_REGION \
              --project $GOOGLE_PROJECT_ID

      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes-deployment.yaml --validate=false
            kubectl rollout restart deployment llmops-app

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image
